name: Scan for Secrets
on:
  label:
    types: [created, deleted]
  pull_request:
    types: [opened, labeled, reopened, synchronize, unlabeled]
  merge_group:
    types: [checks_requested]

env:
  TRUFFLEHOG_VERSION: 3.90.2

jobs:
  trufflehog-binary:
    runs-on: ubuntu-24.04
    name: Prepare Trufflehog Binary
    steps:
      - name: Restore trufflehog binary cache
        id: restore-cache-trufflehog
        uses: actions/cache/restore@v4
        with:
          path: ./trufflehog
          key: trufflehog-cache-${{ runner.os }}-${{ env.TRUFFLEHOG_VERSION }}
      - name: Install Trufflehog
        if: ${{ steps.restore-cache-trufflehog.outputs.cache-hit != 'true' }}
        run: |
          mkdir -p ./trufflehog-bin
          curl -L -o "trufflehog_3.90.2_linux_amd64.tar.gz" "https://github.com/trufflesecurity/trufflehog/releases/download/v3.90.2/trufflehog_3.90.2_linux_amd64.tar.gz"
          tar -xzvf "trufflehog_3.90.2_linux_amd64.tar.gz"
      - name: Cache Trufflehog binary
        id: cache-node-modules
        if: ${{ steps.restore-cache-trufflehog.outputs.cache-hit != 'true' }}
        uses: actions/cache/save@v4
        with:
          path: ./trufflehog
          key: trufflehog-cache-${{ runner.os }}-${{ env.TRUFFLEHOG_VERSION }}
  trufflehog-parent:
    runs-on: ubuntu-24.04
    name: Trufflehog Parent
    needs: [trufflehog-binary]
    steps:
      - name: Check out ${{ github.event.pull_request.base.ref }}
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.base.ref }}
          path: ${{ github.event.repository.name }}
      - name: Restore trufflehog binary cache
        id: restore-cache-trufflehog
        uses: actions/cache/restore@v4
        with:
          path: ./trufflehog
          key: trufflehog-cache-${{ runner.os }}-${{ env.TRUFFLEHOG_VERSION }}
      - name: Run Trufflehog
        env:
          BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
        run: |
          ./trufflehog git file://${{ github.event.repository.name }} --branch "$BASE_BRANCH" --max-depth=1 --no-update --json --only-verified > trufflehog-parent.json
      - name: Upload Trufflehog output
        uses: actions/upload-artifact@v4
        with:
          name: trufflehog-parent
          path: trufflehog-parent.json
          retention-days: 1
  trufflehog-self:
    runs-on: ubuntu-24.04
    name: Trufflehog Self
    needs: [trufflehog-binary]
    steps:
      - name: Check out ${{ github.event.pull_request.head.ref }}
        uses: actions/checkout@v4
        with:
          path: ${{ github.event.repository.name }}
          fetch-depth: 0
      - name: Restore trufflehog binary cache
        id: restore-cache-trufflehog
        uses: actions/cache/restore@v4
        with:
          path: ./trufflehog
          key: trufflehog-cache-${{ runner.os }}-${{ env.TRUFFLEHOG_VERSION }}
      - name: Get commit depth
        run: |
          echo "COMMIT_DEPTH=$(git -C ${{ github.event.repository.name }} rev-list --count HEAD^1..HEAD)" | tee -a $GITHUB_ENV
          echo "HEAD is $(git -C ${{ github.event.repository.name }} rev-parse HEAD)"
          echo "HEAD^1 is $(git -C ${{ github.event.repository.name }} rev-parse HEAD^1)"
          echo "Commits are:"
          echo "$(git -C ${{ github.event.repository.name }} rev-list HEAD^1..HEAD)"
      - name: Run Trufflehog
        env:
          BRANCH_NAME: ${{ github.event.pull_request.head.ref }}
        run: |
          ./trufflehog git file://${{ github.event.repository.name }} --max-depth=$COMMIT_DEPTH --no-update --json --only-verified > trufflehog-self.json
      - name: Upload Trufflehog output
        uses: actions/upload-artifact@v4
        with:
          name: trufflehog-self
          path: trufflehog-self.json
          retention-days: 1
  trufflehog-compare:
    runs-on: ubuntu-24.04
    name: Trufflehog Compare Results
    needs: [trufflehog-parent, trufflehog-self]
    steps:
      - name: Download parent output file
        uses: actions/download-artifact@v4
        with:
          name: trufflehog-parent
      - name: Download self output file
        uses: actions/download-artifact@v4
        with:
          name: trufflehog-self
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: 18.16.1
      - name: Check for newly-added secrets
        run: |
          node <<-'SCRIPT'
          const { readFileSync } = require("fs");
          const { createHash } = require("crypto");
          // Function to create a SHA-256 hash of a given input string
          function createSHA256Hash(input) {
            const hash = createHash("sha256");
            hash.update(input);
            return hash.digest("hex");
          }
          function getUniqueDetectionsFromFile(filename) {
            const detections = [];
            const hashToFileLineMap = new Map();
            const contents = readFileSync(filename, "utf8");
            // console.log(contents);
            const lines = contents.split("\n");
            for (const l of lines) {
              if (l.length === 0) {
                continue;
              }
              const json = JSON.parse(l);
              const {
                SourceMetadata: {
                  Data: {
                    Git: { commit, file, line },
                  },
                },
                Raw,
              } = json;
              const hash = createSHA256Hash(`${commit}:${file}:${Raw}`);
              detections.push(hash);
              hashToFileLineMap.set(hash, `${file}:${line} (commit ${commit})`);
            }
            return [ detections, hashToFileLineMap ];
          }
          // Function to identify elements in B that are NOT in A
          function findElementsNotInA(arrayA, arrayB) {
            return arrayB.filter((element) => !arrayA.includes(element));
          }
          function main() {
            const PARENT = "trufflehog-parent.json";
            const SELF = "trufflehog-self.json";
            const [ parentDetections ] = getUniqueDetectionsFromFile(PARENT);
            const [ selfDetections, hashToFileLineMap ] = getUniqueDetectionsFromFile(SELF);
            const newDetections = findElementsNotInA(parentDetections, selfDetections);
            if (newDetections.length > 0) {
              console.error(`${newDetections.length} New Trufflehog detection(s) found!`);
              console.error(`Since the secret was committed to your development branch, you can't simply delete the key and commit your changes.`);
              console.error(`The git history will need to be cleaned up. You may need to talk to the security team to figure out the best approach.`);
              console.error(`Secrets were found in the following locations:`);
              for (const detection of newDetections) {
                const fileLine = hashToFileLineMap.get(detection);
                console.error(`  - ${fileLine}`);
              }
              process.exit(1);
            }
            console.log("No new secrets detected by Trufflehog!");
            process.exit(0);
          }
          main();
          'SCRIPT'
